### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by il8677** [DyingEcho/clippy#2]
```
Traceback (most recent call last):
  File "clippy.py", line 7, in <module>
    cronJobs	= subprocess.check_output("crontab -l", shell = True)		# jobs stored in cron
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'crontab -l' returned non-zero exit status 1
```

**Comment by DyingEcho** [comment]
Odd, that odesn't show up on my machine. I'll look into it.

**Comment by DyingEcho** [comment]
Are you running Python 2.7? This is on 3.5.
I ask because of:
`File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output`

**Comment by DyingEcho** [comment]
Also, make sure you run it as `/path/to/script/clippy` instead of `python3 ./clippy`.

**Comment by DyingEcho** [comment]
@il8677 Did that fix it?

**Comment by il8677** [comment]
It was a local problem
